# Generated by Django 5.0.7 on 2024-08-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0004_supportrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportrequest',
            name='user',
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
