# Generated by Django 5.0.7 on 2024-08-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0005_remove_supportrequest_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimrequest',
            name='status',
        ),
    ]
