# Generated by Django 5.0.7 on 2024-08-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0007_claimrequest_username_alter_claimrequest_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimrequest',
            old_name='policy',
            new_name='policy_number',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='policy_type',
            field=models.CharField(default='Life Insurance', max_length=100),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
