# Generated by Django 5.0.7 on 2024-08-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0009_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='policy_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='policy',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
